// Task-focused help lives in the app and remains available offline.
import { $, html, setHTML } from "./util.js";

export function init(ctx) {
  const topics = [
    ["start", "Getting started", "Make Jiggered fit your day", html`<p>Start in Today with a green, amber or red check-in. Tap an activity when you do it. Use Episode when you want to record symptoms, and History when you want to review or share your log.</p><p>Your account is created by the person who runs Jiggered. A temporary password must be changed at first sign-in.</p><button class="secondary" data-help-go="today">Open Today</button>`],
    ["points", "Daily energy", "What do points and check-in colours mean?", html`<p>Points are personal planning estimates. Your starting budget is the amount you plan around each day. A positive activity cost spends points; a negative cost records recovery; zero records the activity without changing your balance.</p><p>Green means a normal plan, amber a reduced plan and red essentials only. Tapping the selected colour clears that check-in. Poor sleep reduces the day's starting budget by your chosen amount.</p><p>Your balance can go below zero or above the starting budget. It is a record, not a recommendation to do more. Past days retain their recorded budget.</p><button class="secondary" data-settings="set-budget">Adjust my budget</button>`],
    ["activities", "Daily energy", "Log, correct or reorder activities", html`<p>Tap a preset to log it at the current time. Other activity records a one-off item without adding a preset. Choose a past day with the arrows or date picker; its time field is optional.</p><p>Use Edit beside a logged item to change its name, points or time. Its position stays the same. Corrections and removals offer Undo briefly after the action.</p><p>In Account, drag a list handle to move an item. With a keyboard, focus the handle and use Up, Down, Home or End. Move buttons are also available. Press Escape to cancel a drag. Save settings to keep the new order.</p><button class="secondary" data-settings="set-acts">Personalise my activities</button>`],
    ["episodes", "Episodes", "Record symptoms and finish an ongoing episode", html`<p>Enter when symptoms started, what you noticed, how they came on, a duration and anything relevant from the day or two before. Notes are optional. Save episode to add it to your history.</p><p>Still going keeps an episode visible in Today and Episode. Choose Record when it ended to finish it. An exact end time is optional; it must be between the start and now.</p><p>New times use this device's time zone. Existing captures retain their recorded offset when you edit them. Older records may have no offset.</p><div class="warn"><b>Call 999</b> if symptoms come on suddenly, or with weakness, face drooping, speech problems or severe headache. Don't log first. Outside the UK, use your local emergency number.</div><button class="secondary" data-help-go="episode">Open Episode</button>`],
    ["history", "Review & share", "Find records and share a summary", html`<p>History shows recent check-ins, trends, days and episodes. Filter by date, check-in colour, symptom or ongoing status, or search activities, symptoms, triggers and notes. Clear filters to see everything again.</p><p>Days as CSV and Episodes as CSV download the records matching those filters. The printed summary uses its own period selector. Preview it before printing or saving as PDF; you can exclude private episode notes.</p><p>These are your observations, not a diagnosis. Choose what you want to share with your clinician.</p><button class="secondary" data-help-go="history">Review my history</button>`],
    ["settings", "Personalise", "Personal settings or shared defaults?", html`<p>Account contains your daily budget, sleep cost, date format and activity, symptom and trigger lists. Lists can be reordered with drag, keyboard or move buttons. Save to apply changes; Discard draft removes unfinished edits.</p><p>When your admin adds items to the shared defaults, a notice offers to add just the new ones to the end of your lists; Account also has Add new shared items. Replace with shared defaults starts a draft again from theirs. Review and save to adopt either. Admin edits never rewrite your lists on their own.</p><button class="secondary" data-help-go="account">Open Account</button>`],
    ["restore", "Your data", "Download a backup or restore an export", html`<p>Download everything (JSON) creates a server export that the restore form can read. Resolve queued or refused changes first so the export includes them.</p><p>Choose an export and Preview restore. Keep-existing is the default; replace mode changes matching records, including settings. Review the counts before confirming. A copy of your current server data downloads before the restore commits.</p><p>If records or your selection change after preview, preview again. Invalid records reject the entire restore with a reason. A backup can restore replaced records; it does not remove records newly added by a restore.</p><p>Device recovery files include drafts and unsent changes for manual recovery. They cannot be uploaded to the restore form. Keep all downloads private.</p><button class="secondary" data-help-go="account">Open data tools</button>`],
    ["offline", "Troubleshooting", "Offline, unfinished drafts or refused changes", html`<p>After you've signed in online, Jiggered can open using this device's copy. Changes queue locally and retry when connected. A queued change has not yet reached your server. If storage is blocked or full, keep the page open and download recovery.</p><p>Episode, activity and settings drafts stay on this device for seven days. Acknowledged saves and explicit discard clear the relevant draft. Signing out warns before removing unfinished work.</p><p>Recovery keeps refused or conflicting edits. Retry a refused save, edit a recovered copy where offered, or download it. For a conflict, choose Keep server copy or Use my change. Restoring a deleted record needs an explicit choice.</p><p>If you can't sign in, ask your Jiggered admin to reset your password. There is no email password-reset service.</p><button class="secondary" data-help-go="account">Open recovery and data tools</button>`],
    ["tabs", "Troubleshooting", "Why is this tab read-only?", html`<p>One browser tab owns editing so tabs cannot overwrite each other's queued work. Other tabs can browse and download, and follow changes from the editing tab.</p><p>Close the editing tab, then choose Reload to edit here in the tab you want to use. Close tabs running an older Jiggered version after an upgrade.</p><p>Editing needs a supported browser on HTTPS (or localhost). If your browser reports that coordination is unavailable, ask your admin to check the connection.</p>`],
    ["privacy", "Your data", "Who can see my log?", html`<p>Personal check-ins and episodes belong to your account. Admin screens show account details and record counts, not your log. An admin can reset passwords, and a full database backup contains everyone's data, so use an instance and administrator you trust.</p><p>Device drafts, JSON downloads, CSVs and printed summaries may contain private health data. Keep them on trusted devices. Account lets you change your password, sign out other devices and delete your account.</p><p>Deleting an account permanently removes its server records. Download what you need first.</p>`],
  ];
  const adminTopic = ["admin", "Admin guide", "Maintain shared defaults and support accounts", html`<p>Admin lets you create accounts, reset passwords, revoke sessions, change roles and disable or remove accounts. A new or reset temporary password is shown once; the person changes it at sign-in.</p><p>Shared product defaults set starting budgets and lists for new users. Reorder, add, edit or remove items in the same editor as personal settings, then save. Reload latest defaults after a conflicting change; your draft is kept.</p><p>Existing users keep personal choices unless they adopt shared defaults from Account. The final active admin cannot be removed or demoted. Activity records account-management events; it does not expose personal health logs.</p><p>Database backups contain everyone's data. Connection settings should match your actual reverse-proxy setup.</p><button class="secondary" data-help-go="admin">Open Admin</button>`];
  const list = $("help-topics"), search = $("help-search");
  let role;
  function mount() {
    if (role === ctx.me.role) return; role = ctx.me.role;
  setHTML(list, html`${[...topics,...(role === "admin" ? [adminTopic] : [])].map(([id, category, title, content]) => html`<details class="help-topic" id="help-${id}" data-topic="${id}"><summary><span class="help-category">${category}</span><span>${title}</span></summary><div class="help-answer">${content}</div></details>`)}`);
  }
  mount();
  const filter = () => {
    const query = search.value.trim().toLocaleLowerCase(); let count = 0;
    for (const detail of list.children) { detail.hidden = !detail.textContent.toLocaleLowerCase().includes(query); if (!detail.hidden) count++ }
    $("help-count").textContent = query ? `${count} ${count === 1 ? "topic" : "topics"} found` : "";
    $("help-empty").hidden = count !== 0;
  };
  search.addEventListener("input", filter);
  $("help-clear").addEventListener("click", () => { search.value = ""; filter(); search.focus() });
  $("help-panel").addEventListener("click", e => { const b = e.target.closest("[data-help-go]"); if (b) ctx.go(b.dataset.helpGo) });
  function open(topic) {
    search.value = ""; filter(); ctx.go("help");
    const detail = $("help-" + topic);
    if (detail) { detail.open = true; detail.querySelector("summary").focus(); detail.scrollIntoView({ block: "nearest" }) }
  }
  return { open, render() { mount(); filter() }, show() { mount(); filter() } };
}
